### ISSUE TITLE
Is it ok to translate into Korean?

### ISSUE THREAD

**Issue by Danue1** [vorner/vorner.github.io#1]
First of all, I am a Korean programmer and I have impressively read your article [Why is Rust difficult].
I want to share your writings with Korean programmers.
Would it be okay?

**Comment by vorner** [comment]
Yes, sure :-)

It would be nice if you linked the original, so readers can still find it.

I'll probably stick some permissive license into the repository soon, so people don't have to ask.

**Comment by vorner** [comment]
There's a license now, so closing.
