### ISSUE TITLE
About a more atomic Arc: Darc

### ISSUE THREAD

**Issue by brunoczim** [vorner/vorner.github.io#11]
About this post: https://vorner.github.io/2018/06/24/arc-more-atomic.html

I thought it would be cool to share with you a thing I have created. I called it "Darc: doubly atomic reference counter". 
https://docs.rs/lockfree/0.1.1/lockfree/darc/struct.Darc.html

**Comment by vorner** [comment]
Thanks for the link. It is indeed interesting (I had a fast look, I'll give it a more thorough one) ‒ there are few things that look a bit strange to me.

But as it is not really an issue with this repo, I'll close this one and will open an issue at the lockfree repo about what I find (or shamelessly steal some ideas 😇).
