### ISSUE TITLE
“Mental models around Ok-Wrapping”

### ISSUE THREAD

**Issue by dahosek** [vorner/vorner.github.io#22]
Yeah, it’s not technically an issue, but I don’t see any other way to reach you—I think your thought about using `Result<Privileges, NotAuthorized>` for the `check_credentials` function is a misapprehension of what the return type should be. I would instead return `Privileges` and have `NotAuthorized` be a special case of `Privileges`. I’m still new to Rust so I don’t know what the syntax would be for how I would return this, but in Java, I would have something like 

     enum Privilege { READ, WRITE, DELETE, EXECUTE}
     ...
     EnumSet<Privilege> checkCredentials(String username, String password) {...}

where an empty set as the return would correspond to `NotAuthorized`. I would imagine that all cases of the Operations Report model would devolve to this sort of reconsideration of the structure of the return type rather than trying to extend it using `Result`.

(My e-mail is don.hosek@gmail.com should you care to extend the discussion.)

**Comment by vorner** [comment]
There are many ways to design things.

What I had in mind back than was:

* The Privileges is a set of allowed privileges.
* Empty set is possible and valid and means the user exists, but has no extra privileges.
* If the user doesn't exist at all, or has a wrong password, the error is returned. That's different than user without privileges.
