### ISSUE TITLE
Any chance of an RSS/Atom feed?

### ISSUE THREAD

**Issue by roliver** [vorner/vorner.github.io#5]
Currently subscribed to the "Recent Commits" feed through github which doesn't have the best SNR.

**Comment by vorner** [comment]
I actually tried to enable them some time ago (https://github.com/vorner/vorner.github.io/blob/master/_config.yml#L4), but it seems it doesn't work out of the box. The feed.xml file exists, but it is kind of empty and useless and it is not linked from anywhere.

I'll get to reading documentation of that plugin in few days.

**Comment by vorner** [comment]
I must be doing something wrong, still no luck with setting up the github pages to generate it.

Do you have experience with the jekyll thing? Why it isn't generating the feed (or, it does, but empty one)?

**Comment by roliver** [comment]
I think the issue is that your blog posts need to be in a _posts subdirectory by default:
https://jekyllrb.com/docs/posts/
see also: https://jekyllrb.com/docs/structure/

**Comment by vorner** [comment]
I think it works now. It contains only the new ones, so the old ones stay on the same URL, but that should be OK.
